abbreviations:
     file: "C://Users/admin/OneDrive/Desktop/work_project/de.uke.iam.automapping/src/automapping/german_abbreviation.xlsx"
     name_of_abbreviation_column: "Abbreviation"
     name_of_description_column: "Description"