abbreviations:
     file: "C://Users/admin/OneDrive/Desktop/work_project/de.uke.iam.automapping/src/automapping/german_abbreviation.xlsx"
     name_of_abbreviation_column: "Abbreviation"
     name_of_description_column: "Description"

concepts:
     file: "C://Users/admin/OneDrive/Desktop/work_project/de.uke.iam.automapping/src/automapping/CONCEPT.csv"

synonyms: 
     file: "C://Users/admin/OneDrive/Desktop/work_project/de.uke.iam.automapping/src/automapping/CONCEPT_SYNONYM.csv"

vocabulary_table: 
     file: "C://Users/admin/OneDrive/Desktop/work_project/de.uke.iam.automapping/src/automapping/VOCABULARY.csv"